// Vedic Zodiac Data and Daily Predictions for Pandith Shivaji's Astrology Portal
const zodiacSigns = [
  {
    id: "aries",
    name: "Aries",
    sanskrit: "Mesha (मेष)",
    symbol: "♈",
    dates: "Mar 21 - Apr 19",
    element: "Fire (Agni)",
    ruler: "Mars (Mangala)",
    overview: "Mars brings a strong surge of vitality and leadership today. Auspicious planetary alignment opens doors to overdue ventures.",
    love: "Honest communication resolves recent domestic tensions. Express your heart clearly.",
    career: "A new professional responsibility arrives with high rewards. Trust your strategic instinct.",
    health: "High physical energy, but avoid hasty physical exertion. Drink cooling water.",
    luckyNumber: "9",
    luckyColor: "Crimson Red & Coral",
    gemstone: "Red Coral (Moonga)",
    auspiciousTime: "09:30 AM - 11:15 AM"
  },
  {
    id: "taurus",
    name: "Taurus",
    sanskrit: "Vrishabha (वृषभ)",
    symbol: "♉",
    dates: "Apr 20 - May 20",
    element: "Earth (Prithvi)",
    ruler: "Venus (Shukra)",
    overview: "Venus radiates harmony in personal relationships and financial prospects. A favorable day for property and family matters.",
    love: "Deep mutual understanding strengthens romantic bonds. Expect pleasant surprise from partner.",
    career: "Financial stability improves. Avoid speculative risks; focus on long-term investments.",
    health: "Throat and neck sensitivity. Warm herbal tea and gentle meditation bring peace.",
    luckyNumber: "6",
    luckyColor: "Silk White & Lotus Pink",
    gemstone: "Diamond or White Sapphire",
    auspiciousTime: "02:00 PM - 03:45 PM"
  },
  {
    id: "gemini",
    name: "Gemini",
    sanskrit: "Mithuna (मिथुन)",
    symbol: "♊",
    dates: "May 21 - Jun 20",
    element: "Air (Vayu)",
    ruler: "Mercury (Budha)",
    overview: "Mercury stimulates sharp intellect, fast deal closures, and successful client communications. Travel plans show positive fruit.",
    love: "Engaging conversations rekindle romance. Single Geminis may receive an unexpected message.",
    career: "Creative solutions impress seniors or investors. Excellent time for negotiations.",
    health: "Mental restlessness can disrupt sleep. Practice Pranayama before resting.",
    luckyNumber: "5",
    luckyColor: "Emerald Green & Mint",
    gemstone: "Emerald (Panna)",
    auspiciousTime: "11:00 AM - 12:45 PM"
  },
  {
    id: "cancer",
    name: "Cancer",
    sanskrit: "Karka (कर्क)",
    symbol: "♋",
    dates: "Jun 21 - Jul 22",
    element: "Water (Jala)",
    ruler: "Moon (Chandra)",
    overview: "The Moon elevates emotional intuition and spiritual perception. Listen closely to inner wisdom when making family decisions.",
    love: "Nurturing emotions create warmth at home. Perfect time for family gatherings or reconciliations.",
    career: "Stable workflow. Collaboration with colleagues proves more fruitful than solo efforts.",
    health: "Digestive sensitivity. Opt for light, sattvic meals and hydration.",
    luckyNumber: "2",
    luckyColor: "Pearl White & Silver",
    gemstone: "Natural Pearl (Moti)",
    auspiciousTime: "07:15 AM - 08:45 AM"
  },
  {
    id: "leo",
    name: "Leo",
    sanskrit: "Simha (सिंह)",
    symbol: "♌",
    dates: "Jul 23 - Aug 22",
    element: "Fire (Agni)",
    ruler: "Sun (Surya)",
    overview: "The Sun blesses you with magnetic charm and authority. People gravitate toward your guidance and leadership.",
    love: "Generosity and warmth illuminate your relationship. Plan a memorable evening.",
    career: "Recognition from superiors or authority figures is indicated. Stand tall in presentations.",
    health: "Vitality is robust. Keep blood circulation active with morning sunlight.",
    luckyNumber: "1",
    luckyColor: "Golden Yellow & Saffron",
    gemstone: "Ruby (Manikya)",
    auspiciousTime: "08:00 AM - 10:00 AM"
  },
  {
    id: "virgo",
    name: "Virgo",
    sanskrit: "Kanya (कन्या)",
    symbol: "♍",
    dates: "Aug 23 - Sep 22",
    element: "Earth (Prithvi)",
    ruler: "Mercury (Budha)",
    overview: "Attention to detail and analytical clarity give you an extraordinary edge in resolving pending paperwork and disputes.",
    love: "Practical gestures of care speak louder than words today. Support your loved one's goals.",
    career: "Audit financial records and refine systems. Your efficiency will save valuable resources.",
    health: "Nervous tension can build up. Take mindful walking breaks in nature.",
    luckyNumber: "5",
    luckyColor: "Forest Green & Olive",
    gemstone: "Peridot or Emerald",
    auspiciousTime: "03:30 PM - 05:00 PM"
  },
  {
    id: "libra",
    name: "Libra",
    sanskrit: "Tula (तुला)",
    symbol: "♎",
    dates: "Sep 23 - Oct 22",
    element: "Air (Vayu)",
    ruler: "Venus (Shukra)",
    overview: "Planetary balance brings peace to long-standing dilemmas. Legal or partnership matters swing in your favor.",
    love: "Harmony blossoms effortlessly. Great moment for expressing marriage or commitment intentions.",
    career: "Collaborative contracts and artistic or commercial ventures gain traction.",
    health: "Maintain kidney and hydration balance. Avoid excess sugar or processed foods.",
    luckyNumber: "7",
    luckyColor: "Pastel Blue & Rose Gold",
    gemstone: "Opal or Blue Sapphire",
    auspiciousTime: "04:15 PM - 06:00 PM"
  },
  {
    id: "scorpio",
    name: "Scorpio",
    sanskrit: "Vrishchika (वृश्चिक)",
    symbol: "♏",
    dates: "Oct 23 - Nov 21",
    element: "Water (Jala)",
    ruler: "Mars & Ketu",
    overview: "Deep transformative energy surrounds your chart. A hidden truth comes to light, offering liberation and clarity.",
    love: "Passionate intensity deepens emotional intimacy. Release past grievances.",
    career: "Research, investigation, and strategic planning yield breakthrough insights.",
    health: "Detoxify your routine. Spiritual meditation clears negative mental residue.",
    luckyNumber: "8",
    luckyColor: "Deep Maroon & Black",
    gemstone: "Cat's Eye or Red Coral",
    auspiciousTime: "06:30 PM - 08:00 PM"
  },
  {
    id: "sagittarius",
    name: "Sagittarius",
    sanskrit: "Dhanu (धनु)",
    symbol: "♐",
    dates: "Nov 22 - Dec 21",
    element: "Fire (Agni)",
    ruler: "Jupiter (Brihaspati)",
    overview: "Jupiter's divine grace showers optimism and fortune. Higher knowledge, spiritual pursuits, and long-distance opportunities flourish.",
    love: "Shared spiritual values and mutual travel aspirations bring immense joy.",
    career: "Mentorship and guidance elevate your position. Expansion into new markets is favored.",
    health: "Stretching and hip flexibility exercises will keep joints agile.",
    luckyNumber: "3",
    luckyColor: "Bright Yellow & Turmeric Gold",
    gemstone: "Yellow Sapphire (Pukhraj)",
    auspiciousTime: "10:15 AM - 12:00 PM"
  },
  {
    id: "capricorn",
    name: "Capricorn",
    sanskrit: "Makara (मकर)",
    symbol: "♑",
    dates: "Dec 22 - Jan 19",
    element: "Earth (Prithvi)",
    ruler: "Saturn (Shani)",
    overview: "Saturn rewards discipline and patient perseverance. Delayed results finally begin to materialize into solid milestones.",
    love: "Maturity and steadfast loyalty strengthen familial security.",
    career: "Executive decisions earn respect. Focus on foundational stability over quick gains.",
    health: "Pay attention to bone and knee health. Warm sesame oil massage is highly beneficial.",
    luckyNumber: "4",
    luckyColor: "Navy Blue & Charcoal",
    gemstone: "Blue Sapphire (Neelam)",
    auspiciousTime: "01:00 PM - 02:30 PM"
  },
  {
    id: "aquarius",
    name: "Aquarius",
    sanskrit: "Kumbha (कुम्भ)",
    symbol: "♒",
    dates: "Jan 20 - Feb 18",
    element: "Air (Vayu)",
    ruler: "Saturn & Rahu",
    overview: "Innovative visions and humanitarian connections bring breakthroughs. Unconventional thinking solves complex family riddles.",
    love: "Appreciate your partner's individuality. Meaningful intellectual bonding elevates romance.",
    career: "Technology, networking, and group projects experience positive momentum.",
    health: "Calf and circulation care. Regular stretching and hydration recommended.",
    luckyNumber: "11",
    luckyColor: "Electric Cyan & Royal Purple",
    gemstone: "Hessonite (Gomed) or Amethyst",
    auspiciousTime: "05:00 PM - 06:45 PM"
  },
  {
    id: "pisces",
    name: "Pisces",
    sanskrit: "Meena (मीन)",
    symbol: "♓",
    dates: "Feb 19 - Mar 20",
    element: "Water (Jala)",
    ruler: "Jupiter (Brihaspati)",
    overview: "Divine intuition is at its peak. Spiritual practices and charitable acts manifest blessings and karmic healing.",
    love: "Unconditional empathy and deep tenderness dissolve misunderstandings.",
    career: "Creative and artistic endeavors receive high appreciation. Foreign business blossoms.",
    health: "Ensure restful sleep. Protect foot comfort and stay mindful of emotional boundaries.",
    luckyNumber: "3 & 7",
    luckyColor: "Sea Green & Golden Saffron",
    gemstone: "Yellow Sapphire or Pearl",
    auspiciousTime: "08:30 AM - 10:15 AM"
  }
];
